title: "Catatan Yudha Styawan"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

url: "https://yudhastyawan.github.io/" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# Aux links for the upper right navigation
aux_links:
  "Yudha Styawan on GitHub":
    - "//github.com/yudhastyawan"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 <a href=\"https://github.com/yudhastyawan\">Yudha Styawan</a>. Theme by 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/yudhastyawan/catatan-yudha" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-146437904-1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)